/* Minimal markdown, shared by the panels and the vault reader.
 *
 * Headings, bullets, bold and inline code. A full parser is a dependency
 * bought for a handful of screens, and the vault's own documents are written
 * in a narrow subset. Anything unrecognised renders as its own text rather
 * than disappearing -- silently dropping a line you wrote is worse than
 * rendering it plainly.
 */
/* Minimal markdown: headings, bullets, bold, code. The brief and worklist
 * are generated by us and shaped predictably, so a full parser would be a
 * dependency bought for one screen. Anything unrecognised renders as its own
 * text rather than disappearing. */
export function Markdown({ src, className = 'px-4 py-[13px]' }: { src: string; className?: string }) {
  return (
    <div className={className}>
      {src.split('\n').map((line, i) => {
        const t = line.trim()
        if (!t) return <div key={i} className="h-[9px]" />
        if (t.startsWith('#')) {
          const depth = t.match(/^#+/)![0].length
          return (
            <div
              key={i}
              className={`mb-[6px] mt-[10px] first:mt-0 ${
                depth <= 2
                  ? 'font-mono text-[11px] font-bold uppercase tracking-[0.12em] text-ink-faint'
                  : 'text-[13px] font-semibold text-ink'
              }`}
            >
              {t.replace(/^#+\s*/, '')}
            </div>
          )
        }
        if (/^[-*]\s/.test(t)) {
          return (
            <div key={i} className="mb-[5px] flex gap-[9px] text-[13px] leading-[1.6] text-ink-dim">
              <span className="mt-[7px] h-[4px] w-[4px] shrink-0 rounded-full bg-ink-faint" />
              <span>{inline(t.replace(/^[-*]\s*/, ''))}</span>
            </div>
          )
        }
        return (
          <p key={i} className="m-0 mb-[7px] text-[13px] leading-[1.65] text-ink-dim">
            {inline(t)}
          </p>
        )
      })}
    </div>
  )
}

function inline(text: string): React.ReactNode {
  return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part, i) => {
    if (part.startsWith('**'))
      return <strong key={i} className="font-semibold text-ink">{part.slice(2, -2)}</strong>
    if (part.startsWith('`'))
      return (
        <code key={i} className="rounded-[3px] border border-line bg-elevated px-[4px] py-px font-mono text-[0.88em] text-ink">
          {part.slice(1, -1)}
        </code>
      )
    return <span key={i}>{part}</span>
  })
}

