/* Brief, Inbox and Settings.
 *
 * All three read real routes. Where the data does not exist yet — the brief
 * and worklist are generated by a scheduler that is build-order item 6 — the
 * page says so and names the file it is waiting for, rather than showing
 * placeholder content. An invented morning brief is worse than a missing
 * one, because the invented one gets believed.
 */
import { Markdown } from './Markdown'
import { MODE_ACCENT, MODE_LABEL, type Mode } from './mock'

export interface BriefPayload {
  brief: Doc
  worklist: Doc
}
interface Doc {
  generated: boolean
  markdown: string | null
  path: string
}

export interface InboxPayload {
  items: {
    id: string
    kind: 'proposal' | 'flagged-job' | 'unreadable'
    mode: string
    title: string
    detail: string
    at: string
    confidence?: string | null
  }[]
  counts: { proposals: number; flagged: number }
}

export interface ConfigPayload {
  modes: { mode: string; model: string; disallowed: string[]; allowed: string[] }[]
  permission_cycle: string[]
  excluded_from_cycle: string[]
  prompts_answerable: boolean
}

export function Heading({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <h2 className={`m-0 mb-[14px] font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-ink-faint ${className}`}>
      {children}
    </h2>
  )
}

function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-[3px] border border-line bg-surface">{children}</div>
}

/** A document the generator has not written yet.
 *
 * Names the exact path so the state is checkable rather than merely
 * asserted — you can go and look, which is the difference between a status
 * and a claim. */
function NotGenerated({ what, path }: { what: string; path: string }) {
  return (
    <Card>
      <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
        No {what} yet. The scheduler writes{' '}
        <code className="font-mono text-[11.5px] text-ink-faint">{path}</code> each morning; it is
        not built yet.
      </div>
    </Card>
  )
}

export function Brief({ data }: { data: BriefPayload }) {
  return (
    <>
      <Heading>Today</Heading>
      {data.brief.generated && data.brief.markdown ? (
        <Card>
          <Markdown src={data.brief.markdown} />
        </Card>
      ) : (
        <NotGenerated what="brief" path={data.brief.path} />
      )}

      <Heading className="mt-7">Worklist</Heading>
      {data.worklist.generated && data.worklist.markdown ? (
        <Card>
          <Markdown src={data.worklist.markdown} />
        </Card>
      ) : (
        <NotGenerated what="worklist" path={data.worklist.path} />
      )}
    </>
  )
}

const KIND_LABEL: Record<string, string> = {
  proposal: 'proposal',
  'flagged-job': 'flagged',
  unreadable: 'unreadable',
}

export function Inbox({ data }: { data: InboxPayload }) {
  if (data.items.length === 0) {
    return (
      <>
        <Heading>Inbox</Heading>
        <Card>
          <div className="px-4 py-[13px] text-[12.5px] text-ink-dim">
            Nothing waiting. Proposals and flagged jobs appear here.
          </div>
        </Card>
      </>
    )
  }

  return (
    <>
      <Heading>
        Inbox · {data.counts.proposals} proposal{data.counts.proposals === 1 ? '' : 's'} ·{' '}
        {data.counts.flagged} flagged
      </Heading>
      <Card>
        {data.items.map((item, i) => {
          const accent = MODE_ACCENT[item.mode as Mode] ?? 'var(--color-ink-dim)'
          return (
            <div key={item.id} className={`px-4 py-[12px] ${i ? 'border-t border-line' : ''}`}>
              <div className="mb-[5px] flex items-center gap-[9px]">
                <span className="h-[7px] w-[7px] shrink-0 rounded-[1px]" style={{ background: accent }} />
                <span className="min-w-0 flex-1 truncate text-[13px] text-ink">{item.title}</span>
                {/* An unreadable job is its own state, not a flagged one:
                    the file could not be parsed, so nothing about it is
                    known -- including whether it needs attention. */}
                <span
                  className="shrink-0 rounded-[3px] border px-[6px] py-px font-mono text-[10px]"
                  style={
                    item.kind === 'unreadable'
                      ? { borderColor: 'var(--color-faber)', color: 'var(--color-faber)' }
                      : { borderColor: 'var(--color-line)', color: 'var(--color-ink-faint)' }
                  }
                >
                  {KIND_LABEL[item.kind] ?? item.kind}
                </span>
              </div>
              <div className="pl-[16px] text-[12px] leading-[1.55] text-ink-dim">{item.detail}</div>
              <div className="mt-[5px] pl-[16px] font-mono text-[10.5px] text-ink-faint">
                {MODE_LABEL[item.mode as Mode] ?? item.mode}
                {item.at ? ` · ${item.at.slice(0, 10)}` : ''}
                {item.confidence ? ` · ${item.confidence} confidence` : ''}
              </div>
            </div>
          )
        })}
      </Card>
    </>
  )
}

export function Settings({ data }: { data: ConfigPayload }) {
  return (
    <>
      <Heading>Models and tool policy</Heading>
      {/* Read from the orchestrator rather than restated here, so this cannot
          drift into describing a system that no longer exists. */}
      <Card>
        {data.modes.map((m, i) => (
          <div
            key={m.mode}
            className={`grid grid-cols-[minmax(110px,1fr)_auto_minmax(0,1.6fr)] items-center gap-4 px-4 py-[12px] ${
              i ? 'border-t border-line' : ''
            }`}
          >
            <span className="flex items-center gap-[8px] text-[13px] text-ink">
              <span
                className="h-[8px] w-[8px] shrink-0 rounded-[1px]"
                style={{ background: MODE_ACCENT[m.mode as Mode] ?? 'var(--color-ink-dim)' }}
              />
              {MODE_LABEL[m.mode as Mode] ?? m.mode}
            </span>
            <span className="font-mono text-[11.5px] text-ink-dim">{m.model}</span>
            <span className="font-mono text-[11px] text-ink-faint">
              {m.allowed.length > 0 && (
                <span className="text-ink-dim">{m.allowed.join(' · ')}</span>
              )}
              {m.disallowed.length > 0 && (
                <>
                  {m.allowed.length > 0 && <span> · </span>}
                  never <span className="text-ink-dim">{m.disallowed.join(' ')}</span>
                </>
              )}
            </span>
          </div>
        ))}
      </Card>

      <Heading className="mt-7">Permissions</Heading>
      <Card>
        <div className="px-4 py-[13px]">
          <div className="mb-[10px] flex flex-wrap items-center gap-[6px]">
            {data.permission_cycle.map((p, i) => (
              <span key={p} className="flex items-center gap-[6px]">
                {i > 0 && <span className="font-mono text-[11px] text-ink-faint">→</span>}
                <span className="rounded-[4px] border border-line bg-elevated px-[8px] py-[3px] font-mono text-[11px] text-ink-dim">
                  {p}
                </span>
              </span>
            ))}
            <span className="font-mono text-[11px] text-ink-faint">↺</span>
          </div>
          {/* Stated rather than left absent: a reader who knows the flag
              exists would otherwise read its absence as an oversight. */}
          <div className="space-y-[7px] text-[12px] leading-[1.6] text-ink-faint">
            <p className="m-0">
              {data.excluded_from_cycle.join(', ')} stays settable but is deliberately not in the
              cycle, so it cannot be reached by tapping a key.
            </p>
            {/* Stated because the chip would otherwise imply a prompt that
                never arrives. A hosted session has nobody to ask, so "ask
                each time" resolves to a refusal for anything not on the
                mode's allowed list above. */}
            {!data.prompts_answerable && (
              <p className="m-0">
                A hosted session cannot show a prompt, so{' '}
                <span className="text-ink-dim">manual</span> denies any tool not listed above
                rather than asking. Modes that need more use{' '}
                <span className="text-ink-dim">acceptEdits</span> or{' '}
                <span className="text-ink-dim">auto</span>.
              </p>
            )}
          </div>
        </div>
      </Card>

      <Heading className="mt-7">Prompts and schedule</Heading>
      <Card>
        <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
          The prompt editor, regression runner and schedule controls are not built yet. Prompts
          live in <code className="font-mono text-[11.5px] text-ink-faint">second-brain/prompts/</code>{' '}
          and the regression suite runs with{' '}
          <code className="font-mono text-[11.5px] text-ink-faint">
            python prompts/run_regression.py
          </code>
          .
        </div>
      </Card>
    </>
  )
}
