/* Brief, Inbox and Settings.
 *
 * All three read real routes. Where the data does not exist yet — the brief
 * and worklist are generated by a scheduler that is build-order item 6 — the
 * page says so and names the file it is waiting for, rather than showing
 * placeholder content. An invented morning brief is worse than a missing
 * one, because the invented one gets believed.
 */
import { useState } from 'react'
import { Unreachable } from './Async'
import { put } from './engine'
import { useFetched } from './useFetched'
import { Markdown } from './Markdown'
import { MODE_ACCENT, MODE_LABEL, type Mode } from './domain'

export interface BriefPayload {
  brief: Doc
  worklist: Doc
}
interface Doc {
  generated: boolean
  markdown: string | null
  path: string
}

export interface InboxPayload {
  items: {
    id: string
    kind: 'proposal' | 'flagged-job' | 'unreadable'
    mode: string
    title: string
    detail: string
    at: string
    confidence?: string | null
  }[]
  counts: { proposals: number; flagged: number }
}

export interface BillingPayload {
  list_cost: number
  turns: number
  /** How many of those turns the figure actually covers. */
  priced_turns: number
  since: string | null
  charged: boolean
  basis: string
}

export interface ConfigPayload {
  modes: { mode: string; model: string; disallowed: string[]; allowed: string[] }[]
  permission_cycle: string[]
  excluded_from_cycle: string[]
  prompts_answerable: boolean
}

export function Heading({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <h2 className={`m-0 mb-[14px] font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-ink-faint ${className}`}>
      {children}
    </h2>
  )
}

function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-[3px] border border-line bg-surface">{children}</div>
}

/** A document the generator has not written yet.
 *
 * Names the exact path so the state is checkable rather than merely
 * asserted — you can go and look, which is the difference between a status
 * and a claim. */
function NotGenerated({ what, path }: { what: string; path: string }) {
  return (
    <Card>
      <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
        No {what} yet. The scheduler writes{' '}
        <code className="font-mono text-[11.5px] text-ink-faint">{path}</code> each morning; it is
        not built yet.
      </div>
    </Card>
  )
}

export function Brief({ data }: { data: BriefPayload }) {
  return (
    <>
      <Heading>Today</Heading>
      {data.brief.generated && data.brief.markdown ? (
        <Card>
          <Markdown src={data.brief.markdown} />
        </Card>
      ) : (
        <NotGenerated what="brief" path={data.brief.path} />
      )}

      <Heading className="mt-7">Worklist</Heading>
      {data.worklist.generated && data.worklist.markdown ? (
        <Card>
          <Markdown src={data.worklist.markdown} />
        </Card>
      ) : (
        <NotGenerated what="worklist" path={data.worklist.path} />
      )}
    </>
  )
}

const KIND_LABEL: Record<string, string> = {
  proposal: 'proposal',
  'flagged-job': 'flagged',
  unreadable: 'unreadable',
}

export function Inbox({ data }: { data: InboxPayload }) {
  if (data.items.length === 0) {
    return (
      <>
        <Heading>Inbox</Heading>
        <Card>
          <div className="px-4 py-[13px] text-[12.5px] text-ink-dim">
            Nothing waiting. Proposals and flagged jobs appear here.
          </div>
        </Card>
      </>
    )
  }

  return (
    <>
      <Heading>
        Inbox · {data.counts.proposals} proposal{data.counts.proposals === 1 ? '' : 's'} ·{' '}
        {data.counts.flagged} flagged
      </Heading>
      <Card>
        {data.items.map((item, i) => {
          const accent = MODE_ACCENT[item.mode as Mode] ?? 'var(--color-ink-dim)'
          return (
            <div key={item.id} className={`px-4 py-[12px] ${i ? 'border-t border-line' : ''}`}>
              <div className="mb-[5px] flex items-center gap-[9px]">
                <span className="h-[7px] w-[7px] shrink-0 rounded-[1px]" style={{ background: accent }} />
                <span className="min-w-0 flex-1 truncate text-[13px] text-ink">{item.title}</span>
                {/* An unreadable job is its own state, not a flagged one:
                    the file could not be parsed, so nothing about it is
                    known -- including whether it needs attention. */}
                <span
                  className="shrink-0 rounded-[3px] border px-[6px] py-px font-mono text-[10px]"
                  style={
                    item.kind === 'unreadable'
                      ? { borderColor: 'var(--color-faber)', color: 'var(--color-faber)' }
                      : { borderColor: 'var(--color-line)', color: 'var(--color-ink-faint)' }
                  }
                >
                  {KIND_LABEL[item.kind] ?? item.kind}
                </span>
              </div>
              <div className="pl-[16px] text-[12px] leading-[1.55] text-ink-dim">{item.detail}</div>
              <div className="mt-[5px] pl-[16px] font-mono text-[10.5px] text-ink-faint">
                {MODE_LABEL[item.mode as Mode] ?? item.mode}
                {item.at ? ` · ${item.at.slice(0, 10)}` : ''}
                {item.confidence ? ` · ${item.confidence} confidence` : ''}
              </div>
            </div>
          )
        })}
      </Card>
    </>
  )
}

export function Settings({ data }: { data: ConfigPayload }) {
  return (
    <>
      <Heading>Models and tool policy</Heading>
      {/* Read from the orchestrator rather than restated here, so this cannot
          drift into describing a system that no longer exists. */}
      <Card>
        {data.modes.map((m, i) => (
          <div
            key={m.mode}
            className={`grid grid-cols-[minmax(110px,1fr)_auto_minmax(0,1.6fr)] items-center gap-4 px-4 py-[12px] ${
              i ? 'border-t border-line' : ''
            }`}
          >
            <span className="flex items-center gap-[8px] text-[13px] text-ink">
              <span
                className="h-[8px] w-[8px] shrink-0 rounded-[1px]"
                style={{ background: MODE_ACCENT[m.mode as Mode] ?? 'var(--color-ink-dim)' }}
              />
              {MODE_LABEL[m.mode as Mode] ?? m.mode}
            </span>
            <span className="font-mono text-[11.5px] text-ink-dim">{m.model}</span>
            <span className="font-mono text-[11px] text-ink-faint">
              {m.allowed.length > 0 && (
                <span className="text-ink-dim">{m.allowed.join(' · ')}</span>
              )}
              {m.disallowed.length > 0 && (
                <>
                  {m.allowed.length > 0 && <span> · </span>}
                  never <span className="text-ink-dim">{m.disallowed.join(' ')}</span>
                </>
              )}
            </span>
          </div>
        ))}
      </Card>

      <Heading className="mt-7">Prompts</Heading>
      <Prompts />

      <Heading className="mt-7">Regression suite</Heading>
      <Regression />

      <Heading className="mt-7">Schedule</Heading>
      <Card>
        {/* Honest rather than a control panel for nothing: the scheduler is
            build-order item 6 and does not exist, so there is nothing here
            to switch on. Naming what it will run is more use than a row of
            dead toggles. */}
        <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
          No scheduler yet. It will run three launchd jobs on wake — the morning brief, the
          vault commit, and maintenance — and this is where they will be turned on and off.
        </div>
      </Card>
    </>
  )
}


/* A curiosity, not a setting — which is why it lives on Stats.
 *
 * The engine reports a per-turn figure at API list price. Under a
 * subscription that is not a charge, so it has no business in a settings
 * page where numbers look like things you owe. As a line under the token
 * counts it reads as what it is: what all this would have cost the other
 * way.
 */
export function ListPriceFact({
  data,
  totalTurns,
}: {
  data: BillingPayload
  /** Every turn the token counts above cover. */
  totalTurns: number
}) {
  if (data.list_cost <= 0 || data.priced_turns === 0) return null

  /* The figure only covers turns recorded since the engine's per-turn cost
   * was stored; earlier ones carry a zero. Sitting under token counts that
   * span every turn, it read about 20x low against its own tokens — two
   * measurements of different populations printed as one fact. So when the
   * coverage is partial it says so, rather than quietly implying it is the
   * total. */
  const partial = data.priced_turns < totalTurns

  return (
    <div className="mt-[13px] flex flex-wrap items-baseline gap-x-[7px] gap-y-[3px] border-t border-line pt-[11px] font-mono text-[11.5px]">
      <span className="text-ink-faint">
        on the API,{' '}
        {partial ? `the last ${data.priced_turns.toLocaleString()} of ${totalTurns.toLocaleString()} turns` : 'this'}{' '}
        would have been
      </span>
      <span className="tabular-nums text-ink">${data.list_cost.toFixed(2)}</span>
      {/* Short, because a long disclaimer under a number makes the number
          itself look disputed. */}
      <span className="text-ink-faint">· the subscription covered it</span>
    </div>
  )
}


interface PromptFile {
  id: string
  path: string
  markdown: string | null
}

/* The prompt editor.
 *
 * Editing here rather than in the vault is worth it for one reason: saving
 * re-renders the config dirs immediately, so the loop between changing a
 * prompt and running the suite against it is short. Editing the file in
 * Obsidian and waiting for the next launch is the long version of the same
 * thing.
 */
function Prompts() {
  const data = useFetched<{ prompts: PromptFile[] }>('/v2/prompts')
  const [selected, setSelected] = useState('system')
  const [draft, setDraft] = useState<string | null>(null)
  const [saving, setSaving] = useState<'idle' | 'saving' | 'saved' | 'failed'>('idle')

  if (data === false) return <Unreachable what="the prompts" />
  if (data === null) return <Loading />

  const file = data.prompts.find((p) => p.id === selected)
  const text = draft ?? file?.markdown ?? ''
  const dirty = draft !== null && draft !== (file?.markdown ?? '')

  return (
    <Card>
      <div className="flex items-center gap-[6px] border-b border-line px-[10px] py-[7px]">
        {data.prompts.map((p) => (
          <button
            key={p.id}
            type="button"
            onClick={() => {
              setSelected(p.id)
              setDraft(null)          // an unsaved edit is not carried to another file
              setSaving('idle')
            }}
            className={`rounded-[4px] px-[8px] py-[3px] font-mono text-[11.5px] transition-colors ${
              p.id === selected ? 'bg-elevated text-ink' : 'text-ink-faint hover:text-ink-dim'
            }`}
          >
            {p.id}
          </button>
        ))}
        <span className="ml-auto font-mono text-[10.5px] text-ink-faint">{file?.path}</span>
      </div>

      <textarea
        value={text}
        onChange={(e) => setDraft(e.target.value)}
        spellCheck={false}
        className="h-[280px] w-full resize-y border-0 bg-ground px-[12px] py-[10px] font-mono text-[11.5px] leading-[1.65] text-ink-dim outline-none"
      />

      <div className="flex items-center gap-[10px] border-t border-line px-[12px] py-[8px]">
        <span className="font-mono text-[11px] text-ink-faint">
          {/* Saving re-renders every config dir that composes this file, so
              the change is live for the next session rather than the next
              launch — said plainly, because that is the reason to edit here
              at all. */}
          {saving === 'saved'
            ? 'Saved and re-rendered — live for the next session'
            : saving === 'failed'
              ? 'Could not save'
              : dirty
                ? 'Unsaved changes'
                : 'Saving re-renders every mode that uses this file'}
        </span>
        <button
          type="button"
          disabled={!dirty || saving === 'saving'}
          onClick={async () => {
            setSaving('saving')
            const ok = await put(`/v2/prompts/${selected}`, { markdown: text })
            setSaving(ok ? 'saved' : 'failed')
            if (ok) setDraft(null)
          }}
          className="ml-auto rounded-[4px] px-[11px] py-[4px] font-mono text-[11.5px] text-ground transition-opacity disabled:cursor-not-allowed disabled:opacity-35"
          style={{ background: 'var(--color-noctua)' }}
        >
          Save
        </button>
      </div>
    </Card>
  )
}

interface RegressionCase {
  id: string
  mode: string
  prompt: string
  tests: string
}

/* The regression suite, listed but not run.
 *
 * Reading it is free; running it is one real session per case on production
 * models. Those are different enough to be different routes — and the button
 * says what it will spend before you press it, because a suite that quietly
 * burns the 5h window is one you stop trusting yourself to click.
 */
function Regression() {
  const data = useFetched<{ cases: RegressionCase[]; sessions: number; path: string }>(
    '/v2/regression',
  )
  const [open, setOpen] = useState(false)

  if (data === false) return <Unreachable what="the regression suite" />
  if (data === null) return <Loading />

  return (
    <Card>
      <div className="flex items-center gap-[10px] px-4 py-[12px]">
        <span className="text-[13px] text-ink">
          {data.cases.length} case{data.cases.length === 1 ? '' : 's'}
        </span>
        <span className="font-mono text-[11px] text-ink-faint">
          {/* The cost, before the click. */}
          running spends {data.sessions} sessions on production models
        </span>
        <button
          type="button"
          onClick={() => setOpen(!open)}
          className="ml-auto font-mono text-[11px] text-ink-faint underline decoration-line underline-offset-2 hover:text-ink-dim"
        >
          {open ? 'hide' : 'show cases'}
        </button>
      </div>

      {open && (
        <div className="border-t border-line">
          {data.cases.map((c) => (
            <div key={c.id} className="border-b border-line px-4 py-[9px] last:border-b-0">
              <div className="flex items-baseline gap-[8px]">
                <span className="font-mono text-[11px] text-ink-faint">{c.id}</span>
                <span
                  className="font-mono text-[11px]"
                  style={{ color: MODE_ACCENT[c.mode as Mode] ?? 'var(--color-ink-dim)' }}
                >
                  {c.mode}
                </span>
              </div>
              <div className="mt-[3px] text-[12px] leading-[1.5] text-ink-dim">{c.tests}</div>
            </div>
          ))}
        </div>
      )}

      {/* Not built rather than hidden: running it needs the orchestrator to
          host thirteen sessions and report them back, which is real work and
          not a button. */}
      <div className="border-t border-line px-4 py-[10px] font-mono text-[11px] text-ink-faint">
        Running from here is not built yet — use{' '}
        <span className="text-ink-dim">python prompts/run_regression.py</span> in{' '}
        <span className="text-ink-dim">backend/</span>.
      </div>
    </Card>
  )
}

function Loading() {
  return (
    <div className="rounded-[3px] border border-line bg-surface px-4 py-[13px] text-[12.5px] text-ink-faint">
      Loading…
    </div>
  )
}
