/* Brief, Inbox and Settings.
 *
 * All three read real routes. Where the data does not exist yet — the brief
 * and worklist are generated by a scheduler that is build-order item 6 — the
 * page says so and names the file it is waiting for, rather than showing
 * placeholder content. An invented morning brief is worse than a missing
 * one, because the invented one gets believed.
 */
import { useEffect, useRef, useState } from 'react'
import { Unreachable } from './Async'
import { post, put } from './engine'
import { useFetched } from './useFetched'
import { Markdown } from './Markdown'
import { MODE_ACCENT, MODE_LABEL, type Mode } from './domain'

export interface BriefPayload {
  brief: Doc
  worklist: Doc
}
interface Doc {
  generated: boolean
  markdown: string | null
  path: string
}

export interface InboxPayload {
  items: {
    id: string
    kind: 'proposal' | 'flagged-job' | 'unreadable'
    mode: string
    title: string
    detail: string
    at: string
    confidence?: string | null
    /** Whether accepting would change a file. Many proposals only surface
     *  a status and change nothing, and that is the first thing you need to
     *  know before deciding. */
    changes_files?: boolean
    /** The file the diff edits, if any. */
    target?: string | null
    /** What accepting does to Noctis, in one sentence -- derived from the
     *  diff by the backend, not claimed by the proposal. */
    effect?: string
    /** The whole argument, for the read that a decision deserves. */
    full?: { rationale: string; diff: string; evidence: string; confidence: string }
  }[]
  counts: { proposals: number; flagged: number }
}

export interface RepoPayload {
  repo: null | {
    root: string
    name: string
    branch: string | null
    upstream: string | null
    ahead: number | null
    behind: number | null
    dirty: string[]
    commits: { sha: string; subject: string; at: number; pushed: boolean }[]
    remote: string | null
    github: null | {
      slug: string
      url: string | null
      private: boolean
      default_branch: string | null
      pull_requests: { number: number; title: string; branch: string | null; draft: boolean; mergeable: string | null; url: string | null; checks: 'pass' | 'fail' | 'pending' | null }[]
      issues: { number: number; title: string; url: string | null; labels: string[] }[]
    }
    github_reason: string | null
  }
}

export interface BillingPayload {
  list_cost: number
  turns: number
  /** How many of those turns the figure actually covers. */
  priced_turns: number
  since: string | null
  charged: boolean
  basis: string
}

export interface ConfigPayload {
  modes: { mode: string; model: string; disallowed: string[]; allowed: string[] }[]
  permission_cycle: string[]
  excluded_from_cycle: string[]
  prompts_answerable: boolean
}

export function Heading({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <h2 className={`m-0 mb-[14px] font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-ink-faint ${className}`}>
      {children}
    </h2>
  )
}

function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-[3px] border border-line bg-surface">{children}</div>
}

/** A document the generator has not written yet.
 *
 * Names the exact path so the state is checkable rather than merely
 * asserted — you can go and look, which is the difference between a status
 * and a claim. */
/** The brief, before the scheduler has written one. */
function NotGenerated({ path }: { path: string }) {
  return (
    <Card>
      <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
        No brief yet this morning. The scheduler writes{' '}
        <code className="font-mono text-[11.5px] text-ink-faint">{path}</code> on wake.
      </div>
    </Card>
  )
}

export function Brief({ data }: { data: BriefPayload }) {
  return (
    <>
      <Heading>Today</Heading>
      {data.brief.generated && data.brief.markdown ? (
        <Card>
          <Markdown src={data.brief.markdown} />
        </Card>
      ) : (
        <NotGenerated path={data.brief.path} />
      )}

      <Heading className="mt-7">Worklist</Heading>
      <Worklist initial={data.worklist.markdown ?? ''} path={data.worklist.path} />
    </>
  )
}

const KIND_LABEL: Record<string, string> = {
  proposal: 'proposal',
  'flagged-job': 'flagged',
  unreadable: 'unreadable',
}

export function Inbox({ data, onDecided }: { data: InboxPayload; onDecided?: () => void }) {
  // Decided items disappear at once rather than at the next load: a row
  // that lingers after you dispatch it reads as a decision that failed.
  const [decided, setDecided] = useState<Set<string>>(new Set())
  // A decision that failed says why, under the row it failed on. The first
  // version swallowed the error and left the row as it was, which is
  // indistinguishable from a button that does nothing.
  const [failed, setFailed] = useState<Record<string, string>>({})
  const [open, setOpen] = useState<Set<string>>(new Set())
  const [busy, setBusy] = useState<string | null>(null)
  const items = data.items.filter((i) => !decided.has(i.id))

  if (items.length === 0) {
    return (
      <>
        <Heading>Inbox</Heading>
        <Card>
          <div className="px-4 py-[13px] text-[12.5px] text-ink-dim">
            Nothing waiting. Proposals and flagged jobs appear here.
          </div>
        </Card>
      </>
    )
  }

  const decide = async (id: string, decision: 'accept' | 'reject') => {
    setBusy(id)
    const out = await post<{ decision: string; applied_to: string | null }>(`/v2/inbox/${id}/${decision}`, {})
    setBusy(null)
    if ('error' in out) {
      setFailed((f) => ({ ...f, [id]: out.error }))
      return
    }
    setDecided((d) => new Set(d).add(id))
    onDecided?.()
  }
  const toggle = (id: string) =>
    setOpen((o) => { const n = new Set(o); if (n.has(id)) n.delete(id); else n.add(id); return n })

  return (
    <>
      <Heading>
        Inbox · {data.counts.proposals} proposal{data.counts.proposals === 1 ? '' : 's'} ·{' '}
        {data.counts.flagged} flagged
      </Heading>
      <Card>
        {items.map((item, i) => {
          const accent = MODE_ACCENT[item.mode as Mode] ?? 'var(--color-ink-dim)'
          const isOpen = open.has(item.id)
          return (
            <div key={item.id} className={`px-4 py-[12px] ${i ? 'border-t border-line' : ''}`}>
              <div className="mb-[5px] flex items-center gap-[9px]">
                <span className="h-[7px] w-[7px] shrink-0 rounded-[1px]" style={{ background: accent }} />
                <span className="min-w-0 flex-1 truncate text-[13px] text-ink">{item.title}</span>
                {/* An unreadable job is its own state, not a flagged one:
                    the file could not be parsed, so nothing about it is
                    known -- including whether it needs attention. */}
                <span
                  className="shrink-0 rounded-[3px] border px-[6px] py-px font-mono text-[10px]"
                  style={
                    item.kind === 'unreadable'
                      ? { borderColor: 'var(--color-faber)', color: 'var(--color-faber)' }
                      : { borderColor: 'var(--color-line)', color: 'var(--color-ink-faint)' }
                  }
                >
                  {KIND_LABEL[item.kind] ?? item.kind}
                </span>
              </div>

              {/* Two lines, in the order a decision needs them: what it is,
                  then what saying yes does. The consequence comes from the
                  diff itself, so it cannot be oversold. */}
              <div className="pl-[16px] text-[12px] leading-[1.55] text-ink-dim">{item.detail}</div>
              {item.effect && (
                <div className="mt-[4px] pl-[16px] text-[12px] leading-[1.55] text-ink">
                  <span className="text-ink-faint">→ </span>{item.effect}
                </div>
              )}

              <div className="mt-[6px] flex items-center gap-[10px] pl-[16px] font-mono text-[10.5px] text-ink-faint">
                <span>
                  {MODE_LABEL[item.mode as Mode] ?? item.mode}
                  {item.at ? ` · ${item.at.slice(0, 10)}` : ''}
                  {item.confidence ? ` · ${item.confidence} confidence` : ''}
                  {item.target ? ` · ${item.target}` : ''}
                </span>
                {item.kind === 'proposal' && (
                  <span className="ml-auto flex items-center gap-[4px]">
                    {item.full && (
                      <button type="button" onClick={() => toggle(item.id)}
                              className="rounded-[3px] border border-line px-[7px] py-[2px] text-ink-faint transition-colors hover:bg-elevated hover:text-ink">
                        {isOpen ? 'close' : 'read'}
                      </button>
                    )}
                    {(['accept', 'reject'] as const).map((decision) => (
                      <button
                        key={decision}
                        type="button"
                        disabled={busy === item.id}
                        onClick={() => void decide(item.id, decision)}
                        className="rounded-[3px] border border-line px-[7px] py-[2px] text-ink-faint transition-colors hover:bg-elevated hover:text-ink disabled:opacity-40"
                      >
                        {decision === 'accept' && item.changes_files ? 'accept · apply' : decision}
                      </button>
                    ))}
                  </span>
                )}
              </div>

              {failed[item.id] && (
                <div className="mt-[6px] pl-[16px] font-mono text-[11px]" style={{ color: 'var(--color-faber)' }}>
                  {failed[item.id]}
                </div>
              )}

              {isOpen && item.full && (
                <div className="mt-[10px] ml-[16px] flex flex-col gap-[10px] border-l border-line pl-[12px] text-[12px] leading-[1.6] text-ink-dim">
                  <Section label="rationale"><Markdown src={item.full.rationale} /></Section>
                  {item.full.diff && (
                    <Section label="diff">
                      <pre className="overflow-x-auto whitespace-pre-wrap rounded-[3px] bg-elevated px-[10px] py-[8px] font-mono text-[11px] leading-[1.5]">
                        {item.full.diff.split('\n').map((l, k) => (
                          <div key={k} className={l.startsWith('+') ? 'text-ink' : l.startsWith('-') ? 'text-ink-faint line-through' : 'text-ink-faint'}>{l}</div>
                        ))}
                      </pre>
                    </Section>
                  )}
                  {item.full.evidence && <Section label="evidence"><Markdown src={item.full.evidence} /></Section>}
                  {item.full.confidence && <Section label="confidence"><Markdown src={item.full.confidence} /></Section>}
                </div>
              )}
            </div>
          )
        })}
      </Card>
    </>
  )
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="mb-[3px] font-mono text-[10px] uppercase tracking-[0.08em] text-ink-faint">{label}</div>
      {children}
    </div>
  )
}

/* The repository the showing terminal is in.
 *
 * Read-only on purpose. The local half is what you are looking at -- the
 * branch, what is not on GitHub yet, what is dirty, the last twenty commits
 * with the unpushed ones marked. The GitHub half is what you are being told
 * about -- open pull requests with their checks, open issues -- and it can
 * be absent (offline, signed out, a remote elsewhere) without taking the
 * local half with it. The one action this view wants, push, it asks for in
 * words: a session never pushes, and that rule is what keeps a crashed
 * session from half-shipping; a button here would be that power through
 * another door. */
export function Repo({ data, cwd }: { data: RepoPayload; cwd: string }) {
  const r = data.repo
  if (!r) {
    return (
      <>
        <Heading>Repo</Heading>
        <Card>
          <div className="px-4 py-[13px] text-[12.5px] text-ink-dim">
            <span className="font-mono">{cwd}</span> is not inside a git repository. <span className="text-ink-faint">git init</span> in a terminal starts one.
          </div>
        </Card>
      </>
    )
  }
  const gh = r.github
  const unpushed = r.ahead ?? 0
  return (
    <>
      <Heading>
        Repo · {r.name}{r.branch ? ` · ${r.branch}` : ''}
      </Heading>

      {/* Where it stands, in one line: the numbers that decide what to do
          next, then the sentence that says what that is. */}
      <Card>
        <div className="flex flex-wrap items-center gap-x-[14px] gap-y-[4px] px-4 py-[11px] font-mono text-[11.5px]">
          <span className="text-ink">{r.branch ?? 'detached'}</span>
          {r.upstream ? (
            <>
              <span className={unpushed ? 'text-ink' : 'text-ink-faint'}>↑ {unpushed} not on GitHub</span>
              <span className={r.behind ? 'text-ink' : 'text-ink-faint'}>↓ {r.behind ?? 0} behind</span>
            </>
          ) : (
            <span className="text-ink-faint">no upstream</span>
          )}
          <span className={r.dirty.length ? 'text-ink' : 'text-ink-faint'}>{r.dirty.length} uncommitted</span>
          {gh && (
            <a href={gh.url ?? '#'} target="_blank" rel="noreferrer" className="ml-auto text-ink-dim hover:text-ink">
              {gh.slug} · {gh.private ? 'private' : 'public'} ↗
            </a>
          )}
        </div>
        <div className="border-t border-line px-4 py-[10px] text-[12px] leading-[1.55] text-ink-dim">
          {nextStep(r)}
        </div>
      </Card>

      {r.dirty.length > 0 && (
        <>
          <Heading className="mt-7">Uncommitted</Heading>
          <Card>
            <div className="px-4 py-[9px] font-mono text-[11.5px] leading-[1.7] text-ink-dim">
              {r.dirty.slice(0, 20).map((f) => <div key={f}>{f}</div>)}
              {r.dirty.length > 20 && <div className="text-ink-faint">… and {r.dirty.length - 20} more</div>}
            </div>
          </Card>
        </>
      )}

      <Heading className="mt-7">Commits</Heading>
      <Card>
        {r.commits.map((c, i) => (
          <div key={c.sha} className={`flex items-baseline gap-[10px] px-4 py-[7px] font-mono text-[11.5px] ${i ? 'border-t border-line' : ''}`}>
            <span className="w-[8px] shrink-0 text-center" title={c.pushed ? 'on GitHub' : 'not on GitHub yet'}
                  style={{ color: c.pushed ? 'var(--color-ink-faint)' : 'var(--color-faber)' }}>
              {c.pushed ? '·' : '●'}
            </span>
            <span className="shrink-0 text-ink-faint">{c.sha}</span>
            <span className="min-w-0 flex-1 truncate text-ink">{c.subject}</span>
            <span className="shrink-0 text-ink-faint">{ago(c.at)}</span>
          </div>
        ))}
        {r.commits.length === 0 && <div className="px-4 py-[9px] text-[12px] text-ink-faint">no commits yet</div>}
      </Card>

      <Heading className="mt-7">GitHub</Heading>
      <Card>
        {!gh ? (
          <div className="px-4 py-[11px] text-[12.5px] text-ink-dim">
            Not available: {r.github_reason ?? 'unknown'}.
          </div>
        ) : (
          <>
            <div className="px-4 py-[9px] font-mono text-[11px] text-ink-faint">
              pull requests · {gh.pull_requests.length} open
            </div>
            {gh.pull_requests.map((p) => (
              <div key={p.number} className="flex items-center gap-[10px] border-t border-line px-4 py-[8px] text-[12px]">
                <span className="shrink-0 font-mono text-ink-faint">#{p.number}</span>
                <a href={p.url ?? '#'} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate text-ink hover:underline">{p.title}</a>
                <span className="shrink-0 font-mono text-[10.5px] text-ink-faint">{p.branch}</span>
                {p.draft && <Tag>draft</Tag>}
                {p.checks && <Tag tone={p.checks === 'fail' ? 'bad' : p.checks === 'pass' ? 'good' : undefined}>checks {p.checks}</Tag>}
                {p.mergeable === 'CONFLICTING' && <Tag tone="bad">conflicts</Tag>}
              </div>
            ))}
            {gh.pull_requests.length === 0 && (
              <div className="border-t border-line px-4 py-[8px] text-[12px] text-ink-faint">none — a branch pushed with a PR is how work gets reviewed before it reaches {gh.default_branch ?? 'main'}</div>
            )}
            <div className="border-t border-line px-4 py-[9px] font-mono text-[11px] text-ink-faint">
              issues · {gh.issues.length} open
            </div>
            {gh.issues.map((it) => (
              <div key={it.number} className="flex items-center gap-[10px] border-t border-line px-4 py-[8px] text-[12px]">
                <span className="shrink-0 font-mono text-ink-faint">#{it.number}</span>
                <a href={it.url ?? '#'} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate text-ink hover:underline">{it.title}</a>
                {it.labels.map((l) => <Tag key={l}>{l}</Tag>)}
              </div>
            ))}
            {gh.issues.length === 0 && (
              <div className="border-t border-line px-4 py-[8px] text-[12px] text-ink-faint">none — an issue per piece of work is the backlog a branch and a PR close</div>
            )}
          </>
        )}
      </Card>
    </>
  )
}

/** What to do next, from the numbers -- the sentence a person new to git
 *  needs and a person used to it can skim past. */
function nextStep(r: NonNullable<RepoPayload['repo']>): string {
  if (!r.upstream) return 'This branch has no upstream. `git push -u origin ' + (r.branch ?? 'main') + '` in a terminal publishes it.'
  const parts: string[] = []
  if (r.dirty.length) parts.push(`${r.dirty.length} file${r.dirty.length === 1 ? '' : 's'} changed and not committed — a session commits as it goes, so this is either in progress or forgotten.`)
  if (r.ahead) parts.push(`${r.ahead} commit${r.ahead === 1 ? '' : 's'} on this machine only. \`git push\` in a terminal puts ${r.ahead === 1 ? 'it' : 'them'} on GitHub — a session never pushes; that is yours.`)
  if (r.behind) parts.push(`${r.behind} commit${r.behind === 1 ? '' : 's'} on GitHub that this machine does not have — \`git pull\` before building on it.`)
  if (!parts.length) parts.push('Everything here is on GitHub and nothing is uncommitted.')
  return parts.join(' ')
}

function Tag({ children, tone }: { children: React.ReactNode; tone?: 'good' | 'bad' }) {
  const color = tone === 'bad' ? 'var(--color-faber)' : tone === 'good' ? 'var(--color-noctua)' : 'var(--color-ink-faint)'
  return (
    <span className="shrink-0 rounded-[3px] border px-[6px] py-px font-mono text-[10px]" style={{ borderColor: 'var(--color-line)', color }}>
      {children}
    </span>
  )
}

const ago = (unix: number): string => {
  const s = Math.max(0, Math.floor(Date.now() / 1000 - unix))
  if (s < 60) return 'now'
  if (s < 3600) return `${Math.floor(s / 60)}m`
  if (s < 86400) return `${Math.floor(s / 3600)}h`
  return `${Math.floor(s / 86400)}d`
}

/* Settings is now only things that are true until you change them: the
 * prompts, the regression suite, the schedule. The models table went because
 * a mode's model does not change unless you change it with /model, so a
 * read-only table of five rows saying "opus" four times was a page telling
 * you what you already set. */
export function Settings() {
  return (
    <>
      <Heading>Prompts</Heading>
      <Prompts />

      <Heading className="mt-7">Regression suite</Heading>
      <Regression />

      <Heading className="mt-7">Schedule</Heading>
      <Card>
        {/* Honest rather than a control panel for nothing: the scheduler is
            build-order item 6 and does not exist, so there is nothing here
            to switch on. Naming what it will run is more use than a row of
            dead toggles. */}
        <div className="px-4 py-[13px] text-[12.5px] leading-[1.6] text-ink-dim">
          No scheduler yet. It will run three launchd jobs on wake — the morning brief, the
          vault commit, and maintenance — and this is where they will be turned on and off.
        </div>
      </Card>
    </>
  )
}


/* A curiosity, not a setting — which is why it lives on Stats.
 *
 * The engine reports a per-turn figure at API list price. Under a
 * subscription that is not a charge, so it has no business in a settings
 * page where numbers look like things you owe. As a line under the token
 * counts it reads as what it is: what all this would have cost the other
 * way.
 */
export function ListPriceFact({
  data,
  totalTurns,
}: {
  data: BillingPayload
  /** Every turn the token counts above cover. */
  totalTurns: number
}) {
  if (data.list_cost <= 0 || data.priced_turns === 0) return null

  /* The figure only covers turns recorded since the engine's per-turn cost
   * was stored; earlier ones carry a zero. Sitting under token counts that
   * span every turn, it read about 20x low against its own tokens — two
   * measurements of different populations printed as one fact. So when the
   * coverage is partial it says so, rather than quietly implying it is the
   * total. */
  const partial = data.priced_turns < totalTurns

  return (
    <div className="mt-[13px] flex flex-wrap items-baseline gap-x-[7px] gap-y-[3px] border-t border-line pt-[11px] font-mono text-[11.5px]">
      <span className="text-ink-faint">
        on the API,{' '}
        {partial ? `the last ${data.priced_turns.toLocaleString()} of ${totalTurns.toLocaleString()} turns` : 'this'}{' '}
        would have been
      </span>
      <span className="tabular-nums text-ink">${data.list_cost.toFixed(2)}</span>
      {/* Short, because a long disclaimer under a number makes the number
          itself look disputed. */}
      <span className="text-ink-faint">· the subscription covered it</span>
    </div>
  )
}


interface PromptFile {
  id: string
  path: string
  markdown: string | null
}

/* The prompt editor.
 *
 * Editing here rather than in the vault is worth it for one reason: saving
 * re-renders the config dirs immediately, so the loop between changing a
 * prompt and running the suite against it is short. Editing the file in
 * Obsidian and waiting for the next launch is the long version of the same
 * thing.
 */
function Prompts() {
  const data = useFetched<{ prompts: PromptFile[] }>('/v2/prompts')
  const [selected, setSelected] = useState('system')
  const [draft, setDraft] = useState<string | null>(null)
  const [saving, setSaving] = useState<'idle' | 'saving' | 'saved' | 'failed'>('idle')

  if (data === false) return <Unreachable what="the prompts" />
  if (data === null) return <Loading />

  const file = data.prompts.find((p) => p.id === selected)
  const text = draft ?? file?.markdown ?? ''
  const dirty = draft !== null && draft !== (file?.markdown ?? '')

  return (
    <Card>
      <div className="flex items-center gap-[6px] border-b border-line px-[10px] py-[7px]">
        {data.prompts.map((p) => (
          <button
            key={p.id}
            type="button"
            onClick={() => {
              setSelected(p.id)
              setDraft(null)          // an unsaved edit is not carried to another file
              setSaving('idle')
            }}
            className={`rounded-[4px] px-[8px] py-[3px] font-mono text-[11.5px] transition-colors ${
              p.id === selected ? 'bg-elevated text-ink' : 'text-ink-faint hover:text-ink-dim'
            }`}
          >
            {p.id}
          </button>
        ))}
        <span className="ml-auto font-mono text-[10.5px] text-ink-faint">{file?.path}</span>
      </div>

      <textarea
        value={text}
        onChange={(e) => setDraft(e.target.value)}
        spellCheck={false}
        className="h-[280px] w-full resize-y border-0 bg-ground px-[12px] py-[10px] font-mono text-[11.5px] leading-[1.65] text-ink-dim outline-none"
      />

      <div className="flex items-center gap-[10px] border-t border-line px-[12px] py-[8px]">
        <span className="font-mono text-[11px] text-ink-faint">
          {/* Saving re-renders every config dir that composes this file, so
              the change is live for the next session rather than the next
              launch — said plainly, because that is the reason to edit here
              at all. */}
          {saving === 'saved'
            ? 'Saved and re-rendered — live for the next session'
            : saving === 'failed'
              ? 'Could not save'
              : dirty
                ? 'Unsaved changes'
                : 'Saving re-renders every mode that uses this file'}
        </span>
        <button
          type="button"
          disabled={!dirty || saving === 'saving'}
          onClick={async () => {
            setSaving('saving')
            const ok = await put(`/v2/prompts/${selected}`, { markdown: text })
            setSaving(ok ? 'saved' : 'failed')
            if (ok) setDraft(null)
          }}
          className="ml-auto rounded-[4px] px-[11px] py-[4px] font-mono text-[11.5px] text-ground transition-opacity disabled:cursor-not-allowed disabled:opacity-35"
          style={{ background: 'var(--color-noctua)' }}
        >
          Save
        </button>
      </div>
    </Card>
  )
}

interface RegressionCase {
  id: string
  mode: string
  prompt: string
  tests: string
}

/* The regression suite, listed but not run.
 *
 * Reading it is free; running it is one real session per case on production
 * models. Those are different enough to be different routes — and the button
 * says what it will spend before you press it, because a suite that quietly
 * burns the 5h window is one you stop trusting yourself to click.
 */
function Regression() {
  const data = useFetched<{ cases: RegressionCase[]; sessions: number; path: string }>(
    '/v2/regression',
  )
  const [open, setOpen] = useState(false)

  if (data === false) return <Unreachable what="the regression suite" />
  if (data === null) return <Loading />

  return (
    <Card>
      <div className="flex items-center gap-[10px] px-4 py-[12px]">
        <span className="text-[13px] text-ink">
          {data.cases.length} case{data.cases.length === 1 ? '' : 's'}
        </span>
        <span className="font-mono text-[11px] text-ink-faint">
          {/* The cost, before the click. */}
          running spends {data.sessions} sessions on production models
        </span>
        <button
          type="button"
          onClick={() => setOpen(!open)}
          className="ml-auto font-mono text-[11px] text-ink-faint underline decoration-line underline-offset-2 hover:text-ink-dim"
        >
          {open ? 'hide' : 'show cases'}
        </button>
      </div>

      {open && (
        <div className="border-t border-line">
          {data.cases.map((c) => (
            <div key={c.id} className="border-b border-line px-4 py-[9px] last:border-b-0">
              <div className="flex items-baseline gap-[8px]">
                <span className="font-mono text-[11px] text-ink-faint">{c.id}</span>
                <span
                  className="font-mono text-[11px]"
                  style={{ color: MODE_ACCENT[c.mode as Mode] ?? 'var(--color-ink-dim)' }}
                >
                  {c.mode}
                </span>
              </div>
              <div className="mt-[3px] text-[12px] leading-[1.5] text-ink-dim">{c.tests}</div>
            </div>
          ))}
        </div>
      )}

      {/* Not built rather than hidden: running it needs the orchestrator to
          host thirteen sessions and report them back, which is real work and
          not a button. */}
      <div className="border-t border-line px-4 py-[10px] font-mono text-[11px] text-ink-faint">
        Running from here is not built yet — use{' '}
        <span className="text-ink-dim">python prompts/run_regression.py</span> in{' '}
        <span className="text-ink-dim">backend/</span>.
      </div>
    </Card>
  )
}

function Loading() {
  return (
    <div className="rounded-[3px] border border-line bg-surface px-4 py-[13px] text-[12.5px] text-ink-faint">
      Loading…
    </div>
  )
}


/* The worklist: the one thing here you write rather than read.
 *
 * Editable in place and saved as you stop typing, because a note you have to
 * open another app to add a line to is one you stop adding lines to. Not
 * generated, by decision — a generated worklist is the job list again under
 * a second name.
 */
function Worklist({ initial, path }: { initial: string; path: string }) {
  const [text, setText] = useState(initial)
  /* `failed` is a state, not an absence of one.
   *
   * A failed save used to fall back to `idle`, which renders "yours to
   * keep" -- the same words as a file that is saved and untouched. So the
   * one moment your typing is *not* on disk looked exactly like the moment
   * it certainly is, and the only way to find out was to reload and watch
   * the edit disappear. */
  const [state, setState] = useState<'idle' | 'saving' | 'saved' | 'failed'>('idle')
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)

  /* Debounced rather than saved on every keystroke, and flushed on unmount
   * so navigating away mid-sentence does not lose the sentence. */
  const schedule = (next: string) => {
    setText(next)
    setState('saving')
    if (timer.current) clearTimeout(timer.current)
    timer.current = setTimeout(async () => {
      const ok = await put('/v2/worklist', { markdown: next })
      setState(ok ? 'saved' : 'failed')
    }, 600)
  }

  useEffect(() => () => {
    if (timer.current) clearTimeout(timer.current)
  }, [])

  return (
    <Card>
      <textarea
        value={text}
        onChange={(e) => schedule(e.target.value)}
        onBlur={() => {
          if (timer.current) clearTimeout(timer.current)
          void put('/v2/worklist', { markdown: text })
            .then((ok) => setState(ok ? 'saved' : 'failed'))
        }}
        spellCheck={false}
        placeholder="- things to get done"
        rows={8}
        className="w-full resize-y border-0 bg-transparent px-4 py-[13px] text-[13px] leading-[1.7] text-ink-dim outline-none placeholder:text-ink-faint"
      />
      <div className="flex items-center gap-[8px] border-t border-line px-4 py-[7px] font-mono text-[10.5px] text-ink-faint">
        <span>{path}</span>
        <span className="ml-auto">
          {state === 'saving' ? 'saving…'
            : state === 'saved' ? 'saved'
              : state === 'failed' ? 'not saved — copy this out before leaving'
                : 'yours to keep'}
        </span>
      </div>
    </Card>
  )
}
